# -*- coding: utf-8 -*-
"""Smart Payment Processing System_DhruvSoni_202501100700066_ECE_B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bg0pzG-7FBDcbDmZodOqkBQY56VVxg3_
"""

#DHRUV SONI
#202501100700066
#ECE B
from abc import ABC, abstractmethod

class Payment(ABC):
    def __init__(self, username):
        self.username = username
        self.original_amount = 0
        self.final_amount = 0

    @abstractmethod
    def pay(self, amount):
        pass

    def generate_receipt(self):
        print("\n----- Receipt -----")
        print("User:", self.username)
        print("Original Amount:", self.original_amount)
        print("Final Paid Amount:", self.final_amount)
        print("-------------------\n")

class CreditCardPayment(Payment):
    def pay(self, amount):
        self.original_amount = amount
        gateway_fee = 0.02 * amount
        gst = 0.18 * gateway_fee
        self.final_amount = amount + gateway_fee + gst

        print("Payment done using Credit Card")
        self.generate_receipt()


class UPIPayment(Payment):
    def pay(self, amount):
        self.original_amount = amount

        if amount > 1000:
            cashback = 50
        else:
            cashback = 0

        self.final_amount = amount - cashback

        print("Payment done using UPI")
        print("Cashback:", cashback)
        self.generate_receipt()

class PayPalPayment(Payment):
    def pay(self, amount):
        self.original_amount = amount

        fee = 0.03 * amount
        conversion_fee = 20

        self.final_amount = amount + fee + conversion_fee

        print("Payment done using PayPal")
        self.generate_receipt()


class WalletPayment(Payment):
    def __init__(self, username, balance):
        super().__init__(username)
        self.balance = balance

    def pay(self, amount):
        self.original_amount = amount

        if amount > self.balance:
            print("Payment Failed: Not enough balance")
        else:
            self.balance -= amount
            self.final_amount = amount
            print("Payment done using Wallet")
            print("Remaining Balance:", self.balance)
            self.generate_receipt()


def process_payment(payment, amount):
    payment.pay(amount)


if __name__ == "__main__":
    p1 = CreditCardPayment("Dhruv")
    p2 = UPIPayment("Dhruv")
    p3 = PayPalPayment("Dhruv")
    p4 = WalletPayment("Dhruv", 1500)

    process_payment(p1, 1000)
    process_payment(p2, 1200)
    process_payment(p3, 500)
    process_payment(p4, 2000)
    process_payment(p4, 1000)